version: "3.9"
services:
  backend:
    build: ./apps/backend
    ports:
      - "8000:8000"
    env_file:
      - ./apps/backend/.env

  frontend:
    build: ./apps/frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
